name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
version-template: '$MAJOR.$MINOR.$PATCH'

categories:
  - title: 'üöÄ Features'
    labels:
      - 'breaking'
      - 'enhancement'
      - 'feature'
  - title: 'üêõ Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
      - 'security'
  - title: 'üìñ Documentation'
    labels:
      - 'documentation'
  - title: 'Other Changes'

version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'enhancement'
      - 'feature'
  patch:
    labels:
      - 'bug'
      - 'documentation'
      - 'fix'
      - 'security'
  default: 'minor'

autolabeler:
  - label: 'documentation'
    body:
      - '/documentation/'
    branch:
      - '/docs\/.+/'
    files:
      - '*.md'
    title:
      - '/documentation/i'
      - '/docsi'
  - label: 'bug'
    body:
      - '/bug/'
    branch:
      - '/bug\/.+/'
      - '/fix\/.+/'
    title:
      - '/bug/i'
      - '/fix/i'
  - label: 'feature'
    branch:
      - '/feature\/.+/'
      - '/enhancement\/.+/'
    title:
      - '/feature/i'
      - '/enhancement/i'
  - label: 'breaking'
    body:
      - '/breaking/'
    branch:
      - '/breaking\/.+/'
    title:
      - '/breaking/i'
      - '/major/i'

exclude-labels:
  - 'skip-changelog'

template: |
  # What's Changed

  $CHANGES
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
